### ISSUE TITLE
Error on installation on Linux IA32 Machine

### ISSUE THREAD

**Issue by nviror** [davidtsai/node-geoip2#3]
> node-geoip2@0.10.1 install /home/apple/node_modules/node-geoip2
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/roo                                                                                        t/.node-gyp/4.1.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/apple/node                                                                                        _modules/node-geoip2/.node-gyp"
make: Entering directory `/home/apple/node_modules/node-geoip2/build'
  CC(target) Release/obj.target/libmaxminddb/deps/libmaxminddb/src/maxminddb.o
../deps/libmaxminddb/src/maxminddb.c:2:20: fatal error: config.h: No such file o                                                                                        r directory
compilation terminated.
make: *** [Release/obj.target/libmaxminddb/deps/libmaxminddb/src/maxminddb.o] Er                                                                                        ror 1
make: Leaving directory `/home/apple/node_modules/node-geoip2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_                                                                                        modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                        s.js:200:12)
gyp ERR! System Linux 3.2.0-4-686-pae
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_mod                                                                                        ules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/apple/node_modules/node-geoip2
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN ENOENT ENOENT: no such file or directory, open '/home/apple/package.json                                                                                        '
npm WARN EPACKAGEJSON /home/appleNo description
npm WARN EPACKAGEJSON /home/appleNo repository field.
npm WARN EPACKAGEJSON /home/appleNo README data
npm WARN EPACKAGEJSON /home/appleNo license field.
npm ERR! Linux 3.2.0-4-686-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-geoip2"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! node-geoip2@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-geoip2@0.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-geoip2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-geoip2
npm ERR! There is likely additional logging output above.

**Comment by davidtsai** [comment]
What operating system and version of nodejs?

**Comment by davidtsai** [comment]
Nevermind, I see it in your log.  You're running 32bit Linux, which I haven't added support for.  I don't have access to a 32bit machine in order to create the necessary headers for it.

Autoconf needs to be ran for the libmaxminddb library located in *deps/libmaxminddb* and the *config.h* file copied to the appropriate place in *deps/config*.
